"""Auditable foundations for active-exposure backtests."""

from .accounting import (
    RebalanceResult,
    calculate_rebalance,
    combine_stock_target_weights,
    drift_weights,
    rebalance_after_drift,
)
from .benchmark import (
    build_drifted_benchmark_weights,
    validate_benchmark_replication_weights,
)
from .controller import (
    DEFAULT_RISK_BANDS,
    active_weights_from_oos_probabilities,
    add_expost_mean_exposure_diagnostic,
    build_oos_exposure_schedule,
    build_volatility_control_weights,
    historical_risk_percentile,
    probability_to_active_weight,
    risk_percentile_to_active_weight,
)
from .execution import (
    MissingExecutionDataError,
    build_open_tradeability,
    build_controller_stock_targets,
    simulate_stock_level_controller,
    validate_execution_constraints,
)
from .metrics import (
    AbsolutePerformance,
    RelativePerformance,
    active_cvar,
    assess_benchmark_replication_quality,
    arithmetic_active_returns,
    evaluate_absolute_performance,
    evaluate_relative_performance,
    information_ratio,
    max_drawdown,
    relative_nav,
    summarize_benchmark_replication_quality,
    summarize_controller_performance,
    summarize_crash_episode_losses,
    tracking_error,
)

__all__ = [
    "DEFAULT_RISK_BANDS",
    "AbsolutePerformance",
    "RebalanceResult",
    "RelativePerformance",
    "active_cvar",
    "assess_benchmark_replication_quality",
    "active_weights_from_oos_probabilities",
    "add_expost_mean_exposure_diagnostic",
    "build_oos_exposure_schedule",
    "build_volatility_control_weights",
    "arithmetic_active_returns",
    "calculate_rebalance",
    "combine_stock_target_weights",
    "drift_weights",
    "evaluate_absolute_performance",
    "evaluate_relative_performance",
    "historical_risk_percentile",
    "information_ratio",
    "max_drawdown",
    "probability_to_active_weight",
    "rebalance_after_drift",
    "relative_nav",
    "risk_percentile_to_active_weight",
    "summarize_benchmark_replication_quality",
    "summarize_controller_performance",
    "summarize_crash_episode_losses",
    "tracking_error",
    "validate_benchmark_replication_weights",
    "build_drifted_benchmark_weights",
    "MissingExecutionDataError",
    "build_open_tradeability",
    "build_controller_stock_targets",
    "simulate_stock_level_controller",
    "validate_execution_constraints",
]
